-- AlterTable
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "homeAddress" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "communicationAdministration" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "communicationBilling" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "ParentLearnerLink" ADD COLUMN IF NOT EXISTS "isPayingPerson" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ParentLearnerLink" ADD COLUMN IF NOT EXISTS "billingStatement" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "ParentLearnerLink" ADD COLUMN IF NOT EXISTS "billingInvoice" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "ParentLearnerLink" ADD COLUMN IF NOT EXISTS "billingReceipt" BOOLEAN NOT NULL DEFAULT true;
