"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updatePilot = exports.listPilots = exports.getPilot = exports.createPilot = exports.buildPilotVerificationChecks = exports.isDryRunClean = exports.hasPilotCriticalFailures = exports.computeMigrationPilotStatus = exports.MigrationPilotError = exports.buildMigrationPilot = exports.resolveMigrationSignoffFilePath = exports.updateSignoff = exports.listSignoffs = exports.getSignoff = exports.createSignoff = exports.exportMigrationSignoffPack = exports.computeSignoffStatus = exports.computeApprovedForGoLive = exports.hasMigrationCriticalFailures = exports.MigrationSignoffError = exports.buildMigrationSignoffPack = exports.exportMigrationReconciliationReport = exports.MigrationReconciliationError = exports.reconcileMigrationBatch = exports.exportImportBatchReport = exports.resolveMigrationReportPath = exports.exportValidationReport = exports.MigrationReversalError = exports.reverseMigrationLedgerBatch = exports.MigrationRollbackError = exports.rollbackMigrationBatch = exports.batchHasCreatedTransactions = exports.updateImportBatch = exports.listImportBatchSummaries = exports.listImportBatches = exports.getImportBatch = exports.createMigrationImportBatch = exports.resolveSafeMigrationFilePath = exports.parseStagedMigrationFile = exports.assertLearnerCreateGuard = exports.computeMigrationApplyPreview = exports.MigrationApplyError = exports.applyMigrationStage = exports.MAPPED_CONFIDENCE_THRESHOLD = exports.suggestColumnMappings = exports.readMigrationFileRows = exports.readMigrationFilePreview = exports.getUniversalMigrationStagingDir = exports.ensureUniversalMigrationStagingDir = exports.detectMigrationCategory = void 0;
exports.postSingleMigrationLedgerTransaction = exports.buildApplyLearnerMatchIndex = exports.testMigrationAdapter = exports.resolveMigrationAdapterSource = exports.getMigrationAdapterForSystem = exports.resolveLedgerPostingType = exports.classifyLedgerTransaction = exports.resolveLearnerForRow = exports.learnerMatchKeysInPriorityOrder = exports.isKidESysLearnerClassListPreview = exports.investigateTransactionReadiness = exports.buildMigrationLearnerMatchIndex = exports.computeTransactionReadiness = exports.classifyTransactionReadiness = exports.shouldTransactionBeHistoricalOnly = exports.isLearnerEligibleForNewBilling = exports.csvCell = exports.buildCsvContent = exports.buildMigrationPreflightDashboard = exports.updateRunbook = exports.listRunbooks = exports.getRunbook = exports.createRunbook = exports.isManualOnlyRunbookStep = exports.DA_SILVA_MANUAL_ONLY_STEP_IDS = exports.computeRunbookOverallStatus = exports.buildDefaultDaSilvaSteps = exports.buildDaSilvaRunbook = void 0;
var detectMigrationCategory_1 = require("./detectMigrationCategory");
Object.defineProperty(exports, "detectMigrationCategory", { enumerable: true, get: function () { return detectMigrationCategory_1.detectMigrationCategory; } });
var migrationStagingPath_1 = require("./migrationStagingPath");
Object.defineProperty(exports, "ensureUniversalMigrationStagingDir", { enumerable: true, get: function () { return migrationStagingPath_1.ensureUniversalMigrationStagingDir; } });
Object.defineProperty(exports, "getUniversalMigrationStagingDir", { enumerable: true, get: function () { return migrationStagingPath_1.getUniversalMigrationStagingDir; } });
var readMigrationFilePreview_1 = require("./readMigrationFilePreview");
Object.defineProperty(exports, "readMigrationFilePreview", { enumerable: true, get: function () { return readMigrationFilePreview_1.readMigrationFilePreview; } });
var readMigrationFileRows_1 = require("./readMigrationFileRows");
Object.defineProperty(exports, "readMigrationFileRows", { enumerable: true, get: function () { return readMigrationFileRows_1.readMigrationFileRows; } });
var suggestColumnMappings_1 = require("./suggestColumnMappings");
Object.defineProperty(exports, "suggestColumnMappings", { enumerable: true, get: function () { return suggestColumnMappings_1.suggestColumnMappings; } });
Object.defineProperty(exports, "MAPPED_CONFIDENCE_THRESHOLD", { enumerable: true, get: function () { return suggestColumnMappings_1.MAPPED_CONFIDENCE_THRESHOLD; } });
var applyMigrationStage_1 = require("./applyMigrationStage");
Object.defineProperty(exports, "applyMigrationStage", { enumerable: true, get: function () { return applyMigrationStage_1.applyMigrationStage; } });
Object.defineProperty(exports, "MigrationApplyError", { enumerable: true, get: function () { return applyMigrationStage_1.MigrationApplyError; } });
var computeMigrationApplyPreview_1 = require("./computeMigrationApplyPreview");
Object.defineProperty(exports, "computeMigrationApplyPreview", { enumerable: true, get: function () { return computeMigrationApplyPreview_1.computeMigrationApplyPreview; } });
Object.defineProperty(exports, "assertLearnerCreateGuard", { enumerable: true, get: function () { return computeMigrationApplyPreview_1.assertLearnerCreateGuard; } });
var parseStagedMigrationFile_1 = require("./parseStagedMigrationFile");
Object.defineProperty(exports, "parseStagedMigrationFile", { enumerable: true, get: function () { return parseStagedMigrationFile_1.parseStagedMigrationFile; } });
Object.defineProperty(exports, "resolveSafeMigrationFilePath", { enumerable: true, get: function () { return parseStagedMigrationFile_1.resolveSafeMigrationFilePath; } });
var migrationImportBatchStore_1 = require("./migrationImportBatchStore");
Object.defineProperty(exports, "createMigrationImportBatch", { enumerable: true, get: function () { return migrationImportBatchStore_1.createMigrationImportBatch; } });
Object.defineProperty(exports, "getImportBatch", { enumerable: true, get: function () { return migrationImportBatchStore_1.getImportBatch; } });
Object.defineProperty(exports, "listImportBatches", { enumerable: true, get: function () { return migrationImportBatchStore_1.listImportBatches; } });
Object.defineProperty(exports, "listImportBatchSummaries", { enumerable: true, get: function () { return migrationImportBatchStore_1.listImportBatchSummaries; } });
Object.defineProperty(exports, "updateImportBatch", { enumerable: true, get: function () { return migrationImportBatchStore_1.updateImportBatch; } });
var rollbackMigrationBatch_1 = require("./rollbackMigrationBatch");
Object.defineProperty(exports, "batchHasCreatedTransactions", { enumerable: true, get: function () { return rollbackMigrationBatch_1.batchHasCreatedTransactions; } });
Object.defineProperty(exports, "rollbackMigrationBatch", { enumerable: true, get: function () { return rollbackMigrationBatch_1.rollbackMigrationBatch; } });
Object.defineProperty(exports, "MigrationRollbackError", { enumerable: true, get: function () { return rollbackMigrationBatch_1.MigrationRollbackError; } });
var reverseMigrationLedgerBatch_1 = require("./reverseMigrationLedgerBatch");
Object.defineProperty(exports, "reverseMigrationLedgerBatch", { enumerable: true, get: function () { return reverseMigrationLedgerBatch_1.reverseMigrationLedgerBatch; } });
Object.defineProperty(exports, "MigrationReversalError", { enumerable: true, get: function () { return reverseMigrationLedgerBatch_1.MigrationReversalError; } });
var exportValidationReport_1 = require("./exportValidationReport");
Object.defineProperty(exports, "exportValidationReport", { enumerable: true, get: function () { return exportValidationReport_1.exportValidationReport; } });
Object.defineProperty(exports, "resolveMigrationReportPath", { enumerable: true, get: function () { return exportValidationReport_1.resolveMigrationReportPath; } });
var exportImportBatchReport_1 = require("./exportImportBatchReport");
Object.defineProperty(exports, "exportImportBatchReport", { enumerable: true, get: function () { return exportImportBatchReport_1.exportImportBatchReport; } });
var reconcileMigrationBatch_1 = require("./reconcileMigrationBatch");
Object.defineProperty(exports, "reconcileMigrationBatch", { enumerable: true, get: function () { return reconcileMigrationBatch_1.reconcileMigrationBatch; } });
Object.defineProperty(exports, "MigrationReconciliationError", { enumerable: true, get: function () { return reconcileMigrationBatch_1.MigrationReconciliationError; } });
var exportMigrationReconciliationReport_1 = require("./exportMigrationReconciliationReport");
Object.defineProperty(exports, "exportMigrationReconciliationReport", { enumerable: true, get: function () { return exportMigrationReconciliationReport_1.exportMigrationReconciliationReport; } });
var buildMigrationSignoffPack_1 = require("./buildMigrationSignoffPack");
Object.defineProperty(exports, "buildMigrationSignoffPack", { enumerable: true, get: function () { return buildMigrationSignoffPack_1.buildMigrationSignoffPack; } });
Object.defineProperty(exports, "MigrationSignoffError", { enumerable: true, get: function () { return buildMigrationSignoffPack_1.MigrationSignoffError; } });
Object.defineProperty(exports, "hasMigrationCriticalFailures", { enumerable: true, get: function () { return buildMigrationSignoffPack_1.hasMigrationCriticalFailures; } });
Object.defineProperty(exports, "computeApprovedForGoLive", { enumerable: true, get: function () { return buildMigrationSignoffPack_1.computeApprovedForGoLive; } });
Object.defineProperty(exports, "computeSignoffStatus", { enumerable: true, get: function () { return buildMigrationSignoffPack_1.computeSignoffStatus; } });
var exportMigrationSignoffPack_1 = require("./exportMigrationSignoffPack");
Object.defineProperty(exports, "exportMigrationSignoffPack", { enumerable: true, get: function () { return exportMigrationSignoffPack_1.exportMigrationSignoffPack; } });
var migrationSignoffStore_1 = require("./migrationSignoffStore");
Object.defineProperty(exports, "createSignoff", { enumerable: true, get: function () { return migrationSignoffStore_1.createSignoff; } });
Object.defineProperty(exports, "getSignoff", { enumerable: true, get: function () { return migrationSignoffStore_1.getSignoff; } });
Object.defineProperty(exports, "listSignoffs", { enumerable: true, get: function () { return migrationSignoffStore_1.listSignoffs; } });
Object.defineProperty(exports, "updateSignoff", { enumerable: true, get: function () { return migrationSignoffStore_1.updateSignoff; } });
Object.defineProperty(exports, "resolveMigrationSignoffFilePath", { enumerable: true, get: function () { return migrationSignoffStore_1.resolveMigrationSignoffFilePath; } });
var buildMigrationPilot_1 = require("./buildMigrationPilot");
Object.defineProperty(exports, "buildMigrationPilot", { enumerable: true, get: function () { return buildMigrationPilot_1.buildMigrationPilot; } });
Object.defineProperty(exports, "MigrationPilotError", { enumerable: true, get: function () { return buildMigrationPilot_1.MigrationPilotError; } });
Object.defineProperty(exports, "computeMigrationPilotStatus", { enumerable: true, get: function () { return buildMigrationPilot_1.computeMigrationPilotStatus; } });
Object.defineProperty(exports, "hasPilotCriticalFailures", { enumerable: true, get: function () { return buildMigrationPilot_1.hasPilotCriticalFailures; } });
Object.defineProperty(exports, "isDryRunClean", { enumerable: true, get: function () { return buildMigrationPilot_1.isDryRunClean; } });
Object.defineProperty(exports, "buildPilotVerificationChecks", { enumerable: true, get: function () { return buildMigrationPilot_1.buildPilotVerificationChecks; } });
var migrationPilotStore_1 = require("./migrationPilotStore");
Object.defineProperty(exports, "createPilot", { enumerable: true, get: function () { return migrationPilotStore_1.createPilot; } });
Object.defineProperty(exports, "getPilot", { enumerable: true, get: function () { return migrationPilotStore_1.getPilot; } });
Object.defineProperty(exports, "listPilots", { enumerable: true, get: function () { return migrationPilotStore_1.listPilots; } });
Object.defineProperty(exports, "updatePilot", { enumerable: true, get: function () { return migrationPilotStore_1.updatePilot; } });
var buildDaSilvaRunbook_1 = require("./buildDaSilvaRunbook");
Object.defineProperty(exports, "buildDaSilvaRunbook", { enumerable: true, get: function () { return buildDaSilvaRunbook_1.buildDaSilvaRunbook; } });
Object.defineProperty(exports, "buildDefaultDaSilvaSteps", { enumerable: true, get: function () { return buildDaSilvaRunbook_1.buildDefaultDaSilvaSteps; } });
Object.defineProperty(exports, "computeRunbookOverallStatus", { enumerable: true, get: function () { return buildDaSilvaRunbook_1.computeRunbookOverallStatus; } });
Object.defineProperty(exports, "DA_SILVA_MANUAL_ONLY_STEP_IDS", { enumerable: true, get: function () { return buildDaSilvaRunbook_1.DA_SILVA_MANUAL_ONLY_STEP_IDS; } });
Object.defineProperty(exports, "isManualOnlyRunbookStep", { enumerable: true, get: function () { return buildDaSilvaRunbook_1.isManualOnlyRunbookStep; } });
var migrationRunbookStore_1 = require("./migrationRunbookStore");
Object.defineProperty(exports, "createRunbook", { enumerable: true, get: function () { return migrationRunbookStore_1.createRunbook; } });
Object.defineProperty(exports, "getRunbook", { enumerable: true, get: function () { return migrationRunbookStore_1.getRunbook; } });
Object.defineProperty(exports, "listRunbooks", { enumerable: true, get: function () { return migrationRunbookStore_1.listRunbooks; } });
Object.defineProperty(exports, "updateRunbook", { enumerable: true, get: function () { return migrationRunbookStore_1.updateRunbook; } });
var buildMigrationPreflightDashboard_1 = require("./buildMigrationPreflightDashboard");
Object.defineProperty(exports, "buildMigrationPreflightDashboard", { enumerable: true, get: function () { return buildMigrationPreflightDashboard_1.buildMigrationPreflightDashboard; } });
var migrationReportCsv_1 = require("./migrationReportCsv");
Object.defineProperty(exports, "buildCsvContent", { enumerable: true, get: function () { return migrationReportCsv_1.buildCsvContent; } });
Object.defineProperty(exports, "csvCell", { enumerable: true, get: function () { return migrationReportCsv_1.csvCell; } });
var transactionEligibility_1 = require("./transactionEligibility");
Object.defineProperty(exports, "isLearnerEligibleForNewBilling", { enumerable: true, get: function () { return transactionEligibility_1.isLearnerEligibleForNewBilling; } });
Object.defineProperty(exports, "shouldTransactionBeHistoricalOnly", { enumerable: true, get: function () { return transactionEligibility_1.shouldTransactionBeHistoricalOnly; } });
Object.defineProperty(exports, "classifyTransactionReadiness", { enumerable: true, get: function () { return transactionEligibility_1.classifyTransactionReadiness; } });
var computeTransactionReadiness_1 = require("./computeTransactionReadiness");
Object.defineProperty(exports, "computeTransactionReadiness", { enumerable: true, get: function () { return computeTransactionReadiness_1.computeTransactionReadiness; } });
Object.defineProperty(exports, "buildMigrationLearnerMatchIndex", { enumerable: true, get: function () { return computeTransactionReadiness_1.buildMigrationLearnerMatchIndex; } });
Object.defineProperty(exports, "investigateTransactionReadiness", { enumerable: true, get: function () { return computeTransactionReadiness_1.investigateTransactionReadiness; } });
Object.defineProperty(exports, "isKidESysLearnerClassListPreview", { enumerable: true, get: function () { return computeTransactionReadiness_1.isKidESysLearnerClassListPreview; } });
Object.defineProperty(exports, "learnerMatchKeysInPriorityOrder", { enumerable: true, get: function () { return computeTransactionReadiness_1.learnerMatchKeysInPriorityOrder; } });
Object.defineProperty(exports, "resolveLearnerForRow", { enumerable: true, get: function () { return computeTransactionReadiness_1.resolveLearnerForRow; } });
var classifyLedgerTransaction_1 = require("./classifyLedgerTransaction");
Object.defineProperty(exports, "classifyLedgerTransaction", { enumerable: true, get: function () { return classifyLedgerTransaction_1.classifyLedgerTransaction; } });
Object.defineProperty(exports, "resolveLedgerPostingType", { enumerable: true, get: function () { return classifyLedgerTransaction_1.resolveLedgerPostingType; } });
var resolveMigrationAdapter_1 = require("./resolveMigrationAdapter");
Object.defineProperty(exports, "getMigrationAdapterForSystem", { enumerable: true, get: function () { return resolveMigrationAdapter_1.getMigrationAdapterForSystem; } });
Object.defineProperty(exports, "resolveMigrationAdapterSource", { enumerable: true, get: function () { return resolveMigrationAdapter_1.resolveMigrationAdapterSource; } });
var testMigrationAdapter_1 = require("./testMigrationAdapter");
Object.defineProperty(exports, "testMigrationAdapter", { enumerable: true, get: function () { return testMigrationAdapter_1.testMigrationAdapter; } });
var postMigrationLedgerTransactions_1 = require("./postMigrationLedgerTransactions");
Object.defineProperty(exports, "buildApplyLearnerMatchIndex", { enumerable: true, get: function () { return postMigrationLedgerTransactions_1.buildApplyLearnerMatchIndex; } });
Object.defineProperty(exports, "postSingleMigrationLedgerTransaction", { enumerable: true, get: function () { return postMigrationLedgerTransactions_1.postSingleMigrationLedgerTransaction; } });
