"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MIGRATION_SYSTEM_REGISTRY_SEED = void 0;
const REVIEWED_AT = "2026-05-25T00:00:00.000Z";
/** Initial South African systems research registry — planned/researching only; no overstated readiness. */
exports.MIGRATION_SYSTEM_REGISTRY_SEED = [
    {
        systemId: "kideesys",
        systemName: "Kid-e-Sys",
        vendor: "Kid-e-Sys",
        country: "ZA",
        website: "",
        exportTypes: ["xls", "mixed"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Multi-file XLS export bundles observed in EduClear migration work (class lists, contacts, billing plan, transactions). Adapter contract under active research; live import paths remain legacy-specific.",
        adapterStatus: "researching",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "sasams",
        systemName: "SA-SAMS",
        vendor: "SA-SAMS",
        country: "ZA",
        website: "",
        exportTypes: ["unknown", "mixed"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Adapter v1: conservative filename and header detection, SA-SAMS column normalization, administrative identifier recognition, and readiness testing. Parse/stage not enabled; export layouts vary by province.",
        adapterStatus: "researching",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "d6",
        systemName: "d6",
        vendor: "d6 Technology",
        country: "ZA",
        website: "",
        exportTypes: ["unknown", "mixed"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "School management and communication platform. Export modules and field mappings under review.",
        adapterStatus: "researching",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "adam",
        systemName: "ADAM",
        vendor: "ADAM",
        country: "ZA",
        website: "",
        exportTypes: ["unknown", "mixed"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Independent-school focused platform. Pupil, contact, and fee export patterns being documented.",
        adapterStatus: "researching",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "edadmin",
        systemName: "Ed-admin",
        vendor: "Ed-admin",
        country: "ZA",
        website: "",
        exportTypes: ["unknown", "mixed"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Modular school administration suite. Per-module export types and reconciliation rules not yet signed off.",
        adapterStatus: "researching",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "edupac",
        systemName: "Edupac",
        vendor: "Edupac",
        country: "ZA",
        website: "",
        exportTypes: ["csv", "xls", "xlsx", "unknown"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Spreadsheet-oriented exports expected; column layouts vary by school. Mapping templates not yet validated end-to-end.",
        adapterStatus: "researching",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "staffroom",
        systemName: "Staffroom",
        vendor: "Staffroom",
        country: "ZA",
        website: "",
        exportTypes: ["unknown"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Planned for registry coverage. No export specification or adapter contract yet.",
        adapterStatus: "planned",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "cemis",
        systemName: "CEMIS",
        vendor: "Western Cape Education Department / provincial CEMIS",
        country: "ZA",
        website: "",
        exportTypes: ["database_export", "unknown"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Provincial education management information system. Access and export mechanisms require formal research.",
        adapterStatus: "planned",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "sims",
        systemName: "SIMS",
        vendor: "ESS / SIMS",
        country: "ZA",
        website: "",
        exportTypes: ["unknown", "mixed"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "International MIS used in some South African schools. Export pathways not yet documented for EduClear.",
        adapterStatus: "planned",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "isams",
        systemName: "iSAMS",
        vendor: "iSAMS",
        country: "ZA",
        website: "",
        exportTypes: ["api", "unknown", "mixed"],
        supportsLearners: false,
        supportsParents: false,
        supportsBilling: false,
        supportsTransactions: false,
        supportsStaff: false,
        notes: "Cloud MIS with API and export options. Integration approach not yet scoped for EduClear migration.",
        adapterStatus: "planned",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
    {
        systemId: "generic-excel-csv",
        systemName: "Generic Excel/CSV",
        vendor: "Various / school-provided",
        country: "ZA",
        website: "",
        exportTypes: ["csv", "xls", "xlsx", "mixed"],
        supportsLearners: true,
        supportsParents: true,
        supportsBilling: true,
        supportsTransactions: true,
        supportsStaff: false,
        notes: "Adapter v1: conservative spreadsheet detection, generic column normalization, ambiguity warnings, and readiness testing. Parse/stage not enabled; ambiguous headers require manual review.",
        adapterStatus: "partial",
        templateCount: 0,
        lastReviewedAt: REVIEWED_AT,
    },
];
