import type { ChartAccount } from "./AccountingChartOfAccounts";

export type JournalStatus = "Draft" | "Posted";

export type JournalOrigin = "MANUAL" | "AUTO";

export type JournalSourceModule =
  | "Manual"
  | "Billing"
  | "Expenses"
  | "Banking"
  | "Payroll"
  | "Suppliers";

export type JournalLine = {
  id: string;
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
  memo: string;
};

export type Journal = {
  id: string;
  journalNo: string;
  date: string;
  description: string;
  reference: string;
  notes: string;
  status: JournalStatus;
  lines: JournalLine[];
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  postedAt?: string;
  reversedFromJournalNo?: string;
  origin?: JournalOrigin;
  sourceModule?: JournalSourceModule;
  sourceId?: string;
  sourceFingerprint?: string;
  autoGenerated?: boolean;
};

export type AuditAction = "Created" | "Edited" | "Posted" | "Reversed" | "AutoPosted";

export type AuditEntry = {
  id: string;
  at: string;
  journalNo: string;
  action: AuditAction;
  user: string;
  details: string;
};

export type JournalStore = {
  journals: Journal[];
  audit: AuditEntry[];
};

export const JOURNALS_STORAGE_PREFIX = "educlearAccountingJournals:";
export const COA_STORAGE_PREFIX = "educlearAccountingCOA:";
export const ACCOUNTING_JOURNALS_UPDATED_EVENT = "educlear-accounting-journals-updated";

export function uid(prefix: string) {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

export function journalsKey(schoolId: string) {
  return `${JOURNALS_STORAGE_PREFIX}${schoolId}`;
}

export function coaKey(schoolId: string) {
  return `${COA_STORAGE_PREFIX}${schoolId}`;
}

export function emptyStore(): JournalStore {
  return { journals: [], audit: [] };
}

export function loadJournalStore(schoolId: string): JournalStore {
  if (!schoolId) return emptyStore();
  try {
    const raw = localStorage.getItem(journalsKey(schoolId));
    if (!raw) return emptyStore();
    const parsed = JSON.parse(raw);
    return {
      journals: Array.isArray(parsed?.journals) ? parsed.journals : [],
      audit: Array.isArray(parsed?.audit) ? parsed.audit : [],
    };
  } catch {
    return emptyStore();
  }
}

export function saveJournalStore(schoolId: string, store: JournalStore) {
  if (!schoolId) return;
  localStorage.setItem(journalsKey(schoolId), JSON.stringify(store));
  dispatchJournalsUpdated(schoolId);
}

export function dispatchJournalsUpdated(schoolId: string) {
  if (typeof window === "undefined") return;
  window.dispatchEvent(
    new CustomEvent(ACCOUNTING_JOURNALS_UPDATED_EVENT, {
      detail: { schoolId: String(schoolId || "").trim() },
    })
  );
}

export function loadActiveCoaAccounts(schoolId: string): ChartAccount[] {
  if (!schoolId) return [];
  try {
    const raw = localStorage.getItem(coaKey(schoolId));
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    const accounts: ChartAccount[] = Array.isArray(parsed)
      ? parsed
      : Array.isArray(parsed?.accounts)
        ? parsed.accounts
        : [];
    return accounts.filter((a) => a.active !== false);
  } catch {
    return [];
  }
}

export function roundMoney(value: number) {
  return Math.round((Number(value) || 0) * 100) / 100;
}

export function lineTotals(lines: JournalLine[]) {
  const debit = roundMoney(lines.reduce((s, l) => s + roundMoney(l.debit), 0));
  const credit = roundMoney(lines.reduce((s, l) => s + roundMoney(l.credit), 0));
  const diff = roundMoney(debit - credit);
  return { debit, credit, diff, balanced: Math.abs(diff) < 0.01 };
}

export function journalTotals(journal: Journal) {
  return lineTotals(journal.lines);
}

export function nextJournalNo(journals: Journal[], date: string) {
  const yyyymm = date.slice(0, 4) + date.slice(5, 7);
  const prefix = `JNL-${yyyymm}-`;
  let max = 0;
  for (const j of journals) {
    if (!j.journalNo.startsWith(prefix)) continue;
    const n = parseInt(j.journalNo.slice(prefix.length), 10);
    if (!Number.isNaN(n) && n > max) max = n;
  }
  return `${prefix}${String(max + 1).padStart(3, "0")}`;
}

export function appendAudit(
  audit: AuditEntry[],
  entry: Omit<AuditEntry, "id" | "at"> & { at?: string }
): AuditEntry[] {
  return [
    {
      id: uid("aud"),
      at: entry.at || new Date().toISOString(),
      journalNo: entry.journalNo,
      action: entry.action,
      user: entry.user,
      details: entry.details,
    },
    ...audit,
  ];
}

export function journalOrigin(journal: Journal): JournalOrigin {
  if (journal.origin) return journal.origin;
  return journal.autoGenerated ? "AUTO" : "MANUAL";
}

export function journalSourceModule(journal: Journal): JournalSourceModule {
  if (journal.sourceModule) return journal.sourceModule;
  return "Manual";
}

export function findJournalByFingerprint(store: JournalStore, fingerprint: string): Journal | undefined {
  const key = String(fingerprint || "").trim();
  if (!key) return undefined;
  return store.journals.find((j) => String(j.sourceFingerprint || "").trim() === key);
}
