import { findSchoolPaymentByIdempotencyKey } from "../utils/billingLedgerStore";
import { countPaymentAllocationsReadOnly } from "../utils/paymentAllocationStore";

/** Matches keys generated by Capture Payment (crypto.randomUUID or idem-<ts>-<rand>). */
export const PAYMENT_ATTEMPT_KEY_PATTERN = /^[A-Za-z0-9_-]{1,120}$/;

export type PaymentAttemptStatusPayment = {
  id: string;
  reference: string;
  amount: number;
  date: string;
  method: string;
  createdAt: string;
};

export type PaymentAttemptStatusBody =
  | { success: true; found: false }
  | {
      success: true;
      found: true;
      payment: PaymentAttemptStatusPayment;
      allocationSaved: boolean;
    };

export type PaymentAttemptStatusDecision =
  | { ok: true; body: PaymentAttemptStatusBody }
  | { ok: false; status: 400 | 403; code: string; error: string };

export function isValidPaymentAttemptKey(value: unknown): boolean {
  return typeof value === "string" && PAYMENT_ATTEMPT_KEY_PATTERN.test(value);
}

/**
 * Read-only status for one Capture Payment idempotency key.
 * Scoped strictly to the authenticated school's ledger — another school's key is "not found".
 */
export function lookupPaymentAttemptStatus(input: {
  authorizedSchoolId: string;
  idempotencyKey: unknown;
}): PaymentAttemptStatusDecision {
  const schoolId = String(input.authorizedSchoolId || "").trim();
  if (!schoolId) {
    return { ok: false, status: 403, code: "MISSING_SCHOOL", error: "Missing school authorization" };
  }
  if (!isValidPaymentAttemptKey(input.idempotencyKey)) {
    return {
      ok: false,
      status: 400,
      code: "INVALID_IDEMPOTENCY_KEY",
      error: "Invalid payment attempt key",
    };
  }
  const key = String(input.idempotencyKey);

  const entry = findSchoolPaymentByIdempotencyKey(schoolId, key);
  if (!entry) {
    return { ok: true, body: { success: true, found: false } };
  }

  const paymentId = String(entry.id || "").trim();
  return {
    ok: true,
    body: {
      success: true,
      found: true,
      payment: {
        id: paymentId,
        reference: String(entry.reference || "").trim(),
        amount: Number(entry.amount) || 0,
        date: String(entry.date || "").slice(0, 10),
        method: String(entry.method || "").trim(),
        createdAt: String(entry.createdAt || ""),
      },
      allocationSaved: countPaymentAllocationsReadOnly(schoolId, paymentId) > 0,
    },
  };
}
