-- AlterEnum
ALTER TYPE "BankTransactionMatchStatus" ADD VALUE IF NOT EXISTS 'accepted';
ALTER TYPE "BankTransactionMatchStatus" ADD VALUE IF NOT EXISTS 'rejected';

-- AlterTable
ALTER TABLE "BankStatementImport" ADD COLUMN IF NOT EXISTS "bankName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BankStatementImport" ADD COLUMN IF NOT EXISTS "uploadedBy" TEXT NOT NULL DEFAULT '';
ALTER TABLE "BankStatementImport" ADD COLUMN IF NOT EXISTS "totalRows" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BankStatementImport" ADD COLUMN IF NOT EXISTS "matchedRows" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BankStatementImport" ADD COLUMN IF NOT EXISTS "unmatchedRows" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BankStatementImport" ADD COLUMN IF NOT EXISTS "duplicateRows" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BankStatementImport" ADD COLUMN IF NOT EXISTS "totalAmountImported" DOUBLE PRECISION NOT NULL DEFAULT 0;
